[package]
name = "orbtk"
version = "0.3.0"
authors = [
    "Florian Blasius <flovanpt@posteo.de>",
    "Jeremy Soller <jackpot51@gmail.com>"
]
description = "The Orbital Widget Toolkit"
documentation = "https://docs.rs/orbtk"
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "ui",
]

[lib]
name = "orbtk"
path = "src/lib.rs"

[dependencies]
cssparser = "0.17.0"
lazy_static = "1.2.0"
dces = "0.1.6"
orbclient = "0.3.18"
orbfont = { git = "https://gitlab.redox-os.org/redox-os/orbfont.git" }
orbimage = "0.1.16"
